### ISSUE TITLE
WebRTC??

### ISSUE THREAD

**Issue by sfranzyshen** [crazy7bird/ESP8266---webRTC#1]
https://en.wikipedia.org/wiki/WebRTC

**Comment by crazy7bird** [comment]
Hello, 
Sorry i am knew on github, and i don't know what an issue mean on this site. So i assume i do something wrong ??

Just to be clear, it was a little project for try github.

So in your link it said WebRTC for real time Communication, i'm sorry but my project was about Web Real Time Clock.

Nothing for communication here.

Have a nice day.
